package com.example.heyimhere.database;

import android.util.Log;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

import com.example.heyimhere.PhoneNumberUtils;

@Entity (foreignKeys = {
@ForeignKey(
        entity = Contact.class,
        parentColumns = "number",
        childColumns = "receiver",
        onDelete = ForeignKey.CASCADE
),
@ForeignKey(
        entity = Contact.class,
        parentColumns = "number",
        childColumns = "sender",
        onDelete = ForeignKey.CASCADE
)},
tableName = "messages")
public class Message {
    @PrimaryKey(autoGenerate = true)
    @NonNull
    @ColumnInfo(name = "id")
    public int id;

    @ColumnInfo(name = "body")
    public String body;

    @ColumnInfo(name = "sender", index = true)
    public String sender;

    @ColumnInfo(name = "receiver", index = true)
    public String receiver;

    @ColumnInfo(name = "is_sent")
    public boolean isSent;

    @ColumnInfo(name = "time")
    public String time;

    public Message(String body, String sender, String receiver, boolean isSent, String time) {
        this.id = 0; //Presumably gets replaced by autogenerated key. Testing needed, but stops crashes.
        this.body = body;
        this.sender = PhoneNumberUtils.Clean(sender);
        this.receiver = PhoneNumberUtils.Clean(receiver);
        this.isSent = isSent;
        this.time = time;
    }
}
